server:
  port: 10000
  session:
    timeout: 30
  tomcat:
    max-connections: 800
    uri-encoding: UTF-8
    basedir: /home/azonebuy/tomcat
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  datasource:
    url: jdbc:mysql://47.89.13.215:3306/azonebuy?useUnicode=true&characterEncoding=UTF-8
    username: azonebuy
    password: azone09@com
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true


